Test conditional

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -598,6 +598,55 @@ jobs:
             docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
             docker push "fynarfin/ph-ee-vouchers:$IMAGE_TAG"
 
+  check_for_changes_vouchers:
+    executor: docker-executor
+    steps:
+      - checkout
+      - run:
+          name: Check for changes in Vouchers
+          command: |
+            # Fetch the latest changes
+            git fetch origin
+            
+            # Determine the base branch for the PR
+            if [ -z "$CIRCLE_PULL_REQUEST" ]; then
+              echo "Not a pull request, skipping check."
+              echo "export BUILD_VOUCHERS=false" >> $BASH_ENV
+            else
+              # Extract the PR number from the pull request URL
+              PR_NUMBER=$(basename "$CIRCLE_PULL_REQUEST")
+            
+              # Fetch the base branch for the PR using the GitHub API
+              PR_BASE_BRANCH=$(curl -sSL "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/${PR_NUMBER}" | jq -r .base.ref)
+            
+              # Ensure we have the latest changes from the base branch
+              git fetch origin "$PR_BASE_BRANCH"
+            
+              # Switch to the base branch and pull the latest changes
+              git checkout "$PR_BASE_BRANCH"
+              git pull origin "$PR_BASE_BRANCH"
+            
+              # Checkout back to the branch under test
+              git checkout -
+            
+              # Find the common ancestor (merge-base) between the base branch and the current branch
+              MERGE_BASE=$(git merge-base origin/$PR_BASE_BRANCH HEAD)
+            
+              # Check if there are any changes in the ph-ee-vouchers directory since the common ancestor
+              if git diff --quiet $MERGE_BASE HEAD -- ph-ee-vouchers; then
+                echo "No changes in ph-ee-vouchers, skipping build."
+                echo "export BUILD_VOUCHERS=false" >> $BASH_ENV
+              else
+                echo "Changes detected in ph-ee-vouchers, proceeding with build."
+                echo "export BUILD_VOUCHERS=true" >> $BASH_ENV
+              fi
+            fi
+      - persist_to_workspace:
+          root: .
+          paths:
+            - .
+
+
   build_and_push_vouchers_latest_image:
     executor: docker-executor
     environment:
@@ -606,37 +655,61 @@ jobs:
 
     steps:
       - checkout
+      # Install Docker to build and push the image
       - setup_remote_docker:
           version: 20.10.14
+
+      # Build the Docker image
       - run:
-          name: Build Docker image for ph-ee-vouchers
+          name: Build Docker image
           command: |
-            cd ph-ee-vouchers
-            ./gradlew checkstyleMain
-            ./gradlew bootJar
-            docker build -t fynarfin/ph-ee-vouchers:latest .
-            if [ "$CIRCLE_BRANCH" != "develop" ]; then
-              PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
-              PR_TITLE=$(curl -sSL "https://api.github.com/repos/fynarfin/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
-              JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
-              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY"; fi
-              docker image tag fynarfin/ph-ee-vouchers:latest fynarfin/ph-ee-vouchers:$JIRA_STORY
+            if [ "$BUILD_VOUCHERS"="true" ]; then
+              cd ph-ee-vouchers
+              ./gradlew bootJar
+              docker build -t fynarfin/ph-ee-vouchers:latest .
+              if [ "$CIRCLE_BRANCH" != "develop" ]; then
+                PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
+                PR_TITLE=$(curl -sSL "https://api.github.com/repos/fynarfin/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
+                JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
+                if [ -z "$JIRA_STORY" ]; then
+                  echo "Invalid PR title" && exit 1
+                else
+                  echo "Ticket NO: $JIRA_STORY"
+                  docker image tag fynarfin/ph-ee-vouchers:latest fynarfin/ph-ee-vouchers:$JIRA_STORY
+                fi
+              fi
+            else
+              echo "Skipping build as there are no changes in ph-ee-vouchers."
             fi
+
+      # Log in to DockerHub using environment variables
       - run:
           name: Login to DockerHub
-          command: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
+          command: |
+            if [ "$BUILD_VOUCHERS"="true" ]; then
+              echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
+            else
+              echo "Skipping DockerHub login as there are no changes in ph-ee-vouchers."
+            fi
+
+      # Push the Docker image to DockerHub
       - run:
           name: Push Docker image to DockerHub
           command: |
-            if [ "$CIRCLE_BRANCH" = "develop" ]; then
-              docker push fynarfin/ph-ee-vouchers:latest
+            if [ "$BUILD_VOUCHERS"="true" ]; then
+              if [ "$CIRCLE_BRANCH" = "develop" ]; then
+                docker push fynarfin/ph-ee-vouchers:latest
+              fi
+              if [ "$CIRCLE_BRANCH" != "develop" ]; then
+                PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
+                PR_TITLE=$(curl -sSL "https://api.github.com/repos/fynarfin/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
+                JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
+                docker push fynarfin/ph-ee-vouchers:${JIRA_STORY}
+              fi
+            else
+              echo "Skipping push as there are no changes in ph-ee-vouchers."
             fi
-            if [ "$CIRCLE_BRANCH" != "develop" ]; then
-              PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
-              PR_TITLE=$(curl -sSL "https://api.github.com/repos/fynarfin/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
-              JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
-              docker push fynarfin/ph-ee-vouchers:${JIRA_STORY}
-            fi
+
   build_and_push_message_gateway_tag_image:
     executor: docker-executor
     environment:
@@ -1465,6 +1538,7 @@ workflows:
   version: 2
   build-and-deploy:
     jobs:
+      - check_for_changes_vouchers
       - build_and_push_vouchers_tag_image:
           filters:
             tags:
@@ -1472,6 +1546,8 @@ workflows:
           context:
             - DOCKER
       - build_and_push_vouchers_latest_image:
+          requires:
+            - check_for_changes_vouchers
           context:
             - DOCKER
       - build_and_push_importer_rdbms_tag_image:
